include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CCModule
CCModule_BUNDLE_EXTENSION = bundle
CCModule_FILES = MockupCCModule.m
CCModule_CFLAGS = -fobjc-arc
CCModule_FRAMEWORKS = UIKit
CCModule_PRIVATE_FRAMEWORKS = ControlCenterUIKit
CCModule_INSTALL_PATH = /Library/ControlCenter/Bundles/

include $(THEOS_MAKE_PATH)/bundle.mk
